### ISSUE TITLE
Loaders

### ISSUE THREAD

**Issue by KrasnovPavel** [M3237-CPP/Deep-Space-Deathmatch#1]
Если у нас есть специальная библиотека для загрузчиков, то логично было бы перенести мои туда же.

**Comment by KrasnovPavel** [comment]
Смержь ветки и я добавлю сделаю общую библиотеку.

**Comment by mvv-1** [comment]
Мои шейдеры нужны только мне. Твои загрузчики нужны только тебе. Если нужен инструмент - берёшь и линкуешься к нему, не таща за собой ненужные вещи.
Логично сделать отдельную либу под хэш-чекер или под что-то, в чём нуждается загрузчик, создающий потоки. Шейдеры ему явно не нужны; для инициализации графики всё будет в библиотеке с графикой.
