### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by KrasnovPavel** [M3237-CPP/Deep-Space-Deathmatch#11]
Надо реализовать вычисление упреждения для цели и текущего оружия. Т.е. "Куда надо стрелять, чтобы попасть в цель двигающуюся с данной скоростью, учитывая что скорость пули конечна?"
* Код вычисления упреждения поместить в Controller.
  * Скорость пули можно получить через Weapon::bulletRelativeLinearVelocity().
* AIController должен использовать упреждение.
* Дедлайн -- среда.

**Comment by Gzernov** [comment]
сделал

**Comment by KrasnovPavel** [comment]
Молодец, теперь он слишком меткий. :)
