### ISSUE TITLE
Inertia damper

### ISSUE THREAD

**Issue by KrasnovPavel** [M3237-CPP/Deep-Space-Deathmatch#13]
Написать гашение угловой скорости корабля для KeyboardController.
* Код разместить в виде отдельной функции, которая вызывается в конце run().
* Функция должна проверять вращается ли корабль по определённой оси и если да, то:
  * Смотреть нажаты ли клавиши для сооветствующей оси (pitchButtonPressed и т.д.) и если не нажаты, то гасить вращение по этой оси; если нажаты, то ничего делать не надо.

Успеешь сделать до завтра?

**Comment by Gzernov** [comment]
сделал
