### ISSUE TITLE
AI guidance

### ISSUE THREAD

**Issue by KrasnovPavel** [M3237-CPP/Deep-Space-Deathmatch#5]
Реализовать разворот и таран неподвижно стоящего корабля. 
* Под тараном понимается что управляемый корабль __носом__ врежется в цель.
* radar->targetPosition() местоположение цели относительно управляемого в локальных координатах.
  * Управляемый корабль смотрит на цель, когда radar->targetPosition()==btVector(0, 0, distance)
* Управление главным двигателем:
  * setPower()
  * increasePower()
  * decreasePower()
* Поворот корабля: через функции Yaw, Roll, Pitch.
* Управление кораблём производится в функции AIController::run() которая вызывается каждый кадр.
* Вид можно переключить в конструкторе DebugDrawer.
* Писать код в ветке AI-Test. Самому merge в master __не__ делать.
* Дедлайн - пятница.

**Comment by KrasnovPavel** [comment]
Представь, что у тебя корабль уже вращается (например из-за столкновения), и тебе надо сориентировать корабль в такой ситуации.

**Comment by Gzernov** [comment]
Сделаю, но не обещаю что скоро (ближе к выходным или в выходные)

**Comment by KrasnovPavel** [comment]
По идее это было частью предыдущего задания.

**Comment by Gzernov** [comment]
Ну понимаю, просто времени нет пока. Как только смогу так сразу пофикшу

**Comment by KrasnovPavel** [comment]
Баги: 27e7bad

**Comment by Gzernov** [comment]
Пофиксил. Плюс должно работать при рандомной начальной угловой скорости

**Comment by KrasnovPavel** [comment]
Надо создать класс MissileController наследник Controller, реализовать в нём это поведение.
* Взрыв реализовать как вызов функции MissileController::explode().
* Каждый кадр проверять расстояние до цели, при расстоянии меньше чем Warhead::damageRadius взрывать.
  * Доступ к warhead реализовать так же как в Controller реализован доступ к другим подсистемам (см. Controller::findSubsystems()). 
* Надо помнить, что количество энергии PowerGrid::thrusterEnergyCurrent ограниченно. При 0 взрыв.
* Дедлайн -- желательно к паре в четверг. Извини, что так поздно, но тут работы на пол часа.

**Comment by Gzernov** [comment]
Окей, постараюсь сегодня сделать.

P.S. Ну тут скорее я должен извиняться, что так затянул с прошлым заданием

**Comment by Gzernov** [comment]
Сделал

**Comment by KrasnovPavel** [comment]
Помнишь наш разговор о функции initialize()? 
Там запрос данных радара, без проверки на существование радара. 
Я это исправил(e329d7f), но больше так не делай.
