### ISSUE TITLE
AI chasing and firing

### ISSUE THREAD

**Issue by KrasnovPavel** [M3237-CPP/Deep-Space-Deathmatch#6]
Это задание гораздо сложнее.
* Надо реализовать удержание цели на расстоянии ~7 метров при низкой относительной скорости. 
* Корабль должен, выйдя на дистанцию, стрелять в цель.
* Цель может быть как неподвижной, так и управляемой с клавиатуры.
* Надо отметить, что стрельба сильно толкает как стреляющий корабль, так и корабль в который попала пуля.
* Дедлайн - 16 ноября.

**Comment by Gzernov** [comment]
Принято

**Comment by KrasnovPavel** [comment]
В KeyboardController::run() можно отключить стрельбу fire() или движение вперёд setPower(0.02), сделав тем самым корабль неподвижным. Ещё ты наверное уже заметил новую систему повреждений из-за которой при ударе носом отключается PowerGrid питающий все двигатели, и иногда Radar в результате чего вместо координат приходит NAN.

**Comment by Gzernov** [comment]
* Пока что я хочу сделать, чтобы мой корабль догонял чужой и держался на расстоянии, чтобы выстрелить
* Да, это я заметил

**Comment by KrasnovPavel** [comment]
Ещё, не стоит несколько раз вызывать createObject() для одного и того же контроллера несколько раз. Срабатывает только последний вызов.

**Comment by KrasnovPavel** [comment]
Теперь срабатывает только первый вызов createObject().

**Comment by KrasnovPavel** [comment]
Использовать m_object->speed() нельзя, и в этом нет смысла m_object->speed() возвращает абсолютную скорость объекта, а radar->targetSpeed() относительную скорость цели. После мержа это не будет собираться т.к. я сделал PhysicsObject::speed() приватной. 
Еще вместо Radar::targetPosition() лучше использовать Controller::targetPosition(), который проверяет существование радара.

**Comment by Gzernov** [comment]
Исправлю

**Comment by KrasnovPavel** [comment]
Нужны тесты когда корабли не в одной горизонтальной плоскости.

**Comment by Gzernov** [comment]
Добавил. Не уверен пока, что работает всегда хорошо

**Comment by KrasnovPavel** [comment]
Что-то он почти не стреляет.

**Comment by KrasnovPavel** [comment]
А ещё я добавил управление с клавиатуры.

**Comment by Gzernov** [comment]
Он стрелял часто но неточно. Сейчас стреляет если скорее всего попадет. Можно константы поменять, чтобы стрелял чаще, но менее точно либо наоборот

**Comment by KrasnovPavel** [comment]
Вроде работает.
